In [34]:
print("all OK")

all OK


## OneHotEncoder

https://scikit-learn.org/stable/modules/generated/sklearn.preprocessing.OneHotEncoder.html

In [35]:

from sklearn.preprocessing import OneHotEncoder
import numpy

In [36]:
documents = ["people watch movie", 
             "people watch cricket", 
             "people like movie", 
             "people like cricket"]

In [37]:
tokens=[sentence.lower().split() for sentence in documents]
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

In [38]:
all_words_sentence = [[sentence_words] for sentence_words in tokens ]
all_words_sentence

[[['people', 'watch', 'movie']],
 [['people', 'watch', 'cricket']],
 [['people', 'like', 'movie']],
 [['people', 'like', 'cricket']]]

### understanding the below code as its list comprehenssion and nested for loop

In [39]:
# understanding the below code as its list comprehenssion and nested for loop

all_words = [[word] for sentence_words in tokens for word in sentence_words]
all_words

[['people'],
 ['watch'],
 ['movie'],
 ['people'],
 ['watch'],
 ['cricket'],
 ['people'],
 ['like'],
 ['movie'],
 ['people'],
 ['like'],
 ['cricket']]

In [40]:
encoder = OneHotEncoder(sparse_output=False)

In [41]:

encoder.fit(all_words)

OneHotEncoder(sparse_output=False)

In [42]:
encoder.categories_

[array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)]

In [43]:
encoder.categories_[0]

array(['cricket', 'like', 'movie', 'people', 'watch'], dtype=object)

In [44]:
print("Vocabulary:", encoder.categories_[0])

Vocabulary: ['cricket' 'like' 'movie' 'people' 'watch']


In [45]:
tokens

[['people', 'watch', 'movie'],
 ['people', 'watch', 'cricket'],
 ['people', 'like', 'movie'],
 ['people', 'like', 'cricket']]

### Word level encoding

In [46]:
for sentence in tokens:
    print("Sentence:", sentence)
    for word in sentence:
        print("Word:", word)
        encoded_word = encoder.transform([[word]])
        print("Encoded Word:", encoded_word)

Sentence: ['people', 'watch', 'movie']
Word: people
Encoded Word: [[0. 0. 0. 1. 0.]]
Word: watch
Encoded Word: [[0. 0. 0. 0. 1.]]
Word: movie
Encoded Word: [[0. 0. 1. 0. 0.]]
Sentence: ['people', 'watch', 'cricket']
Word: people
Encoded Word: [[0. 0. 0. 1. 0.]]
Word: watch
Encoded Word: [[0. 0. 0. 0. 1.]]
Word: cricket
Encoded Word: [[1. 0. 0. 0. 0.]]
Sentence: ['people', 'like', 'movie']
Word: people
Encoded Word: [[0. 0. 0. 1. 0.]]
Word: like
Encoded Word: [[0. 1. 0. 0. 0.]]
Word: movie
Encoded Word: [[0. 0. 1. 0. 0.]]
Sentence: ['people', 'like', 'cricket']
Word: people
Encoded Word: [[0. 0. 0. 1. 0.]]
Word: like
Encoded Word: [[0. 1. 0. 0. 0.]]
Word: cricket
Encoded Word: [[1. 0. 0. 0. 0.]]


### Document / Sentence level encoding

In [47]:

for sentence in tokens:
    encoded_sentence = encoder.transform([[word] for word in sentence])
    print("\nSentence:", sentence)
    print(encoded_sentence)
     


Sentence: ['people', 'watch', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'watch', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0.]]

Sentence: ['people', 'like', 'movie']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]

Sentence: ['people', 'like', 'cricket']
[[0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0.]
 [1. 0. 0. 0. 0.]]


## BOW

https://scikit-learn.org/0.15/modules/generated/sklearn.feature_extraction.text.CountVectorizer.html

In [48]:

from sklearn.feature_extraction.text import CountVectorizer

In [49]:

documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]
     

In [50]:
bow = CountVectorizer()


In [51]:
bow_matrix=bow.fit_transform(documents)

In [52]:
print("bow_matrix:", bow_matrix.toarray())

bow_matrix: [[1 1 0 0 0 2 1 2]
 [0 1 2 0 0 0 1 2]
 [0 1 0 2 1 2 1 0]
 [0 0 1 1 0 0 1 0]]


In [53]:
print("Vocabulary:", bow.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


In [54]:
sentence = ["people need to watch news"]

In [55]:
bow_matrix=bow.transform(sentence)
print("bow_matrix:", bow_matrix.toarray())

bow_matrix: [[0 0 0 0 0 0 1 1]]


##### Observe - "need" "to" "news" words are totally missing in BOW representation

In [56]:
print("Vocabulary:", bow.get_feature_names_out())


Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


### TD-IDF

In [57]:
from sklearn.feature_extraction.text import TfidfVectorizer


In [58]:

documents = ["people watch movie and watch movie again", 
             "people watch cricket and watch cricket",
             "people like movie and like movie a lot",
             "people like cricket"]

In [59]:

tf_idf = TfidfVectorizer()

In [60]:
tf_idf_vector = tf_idf.fit_transform(documents)

In [61]:
tf_idf_vector

<4x8 sparse matrix of type '<class 'numpy.float64'>'
	with 17 stored elements in Compressed Sparse Row format>

In [66]:
# call on tf-idf object to get the feature names (vocabulary) of the documents
print("Vocabulary:", tf_idf.get_feature_names_out())

Vocabulary: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']


In [65]:
# call to_array on transformed by tf-idf model to get the tf-idf matrix of the documents
print("Matrix\n", tf_idf_vector.toarray())

Matrix
 [[0.38771136 0.24747114 0.         0.         0.         0.61135218
  0.20232387 0.61135218]
 [0.         0.2684707  0.66322944 0.         0.         0.
  0.21949239 0.66322944]
 [0.         0.24747114 0.         0.61135218 0.38771136 0.61135218
  0.20232387 0.        ]
 [0.         0.         0.64043405 0.64043405 0.         0.
  0.42389674 0.        ]]


In [77]:
# help me in printing the tf-idf matrix in a more readable format with the feature names as column headers and the documents as row headers. and reduce numbers after decimal point to 4
import numpy as np

np.set_printoptions(precision=4, suppress=True)

for doc_index, doc in enumerate(documents):
    print(f"Document {doc_index + 1}: {doc}")

print("TF-IDF Matrix:")
print("Feature Names:", tf_idf.get_feature_names_out())
print()

print("TF-IDF Matrix:")
print(tf_idf_vector.toarray())


Document 1: people watch movie and watch movie again
Document 2: people watch cricket and watch cricket
Document 3: people like movie and like movie a lot
Document 4: people like cricket
TF-IDF Matrix:
Feature Names: ['again' 'and' 'cricket' 'like' 'lot' 'movie' 'people' 'watch']

TF-IDF Matrix:
[[0.3877 0.2475 0.     0.     0.     0.6114 0.2023 0.6114]
 [0.     0.2685 0.6632 0.     0.     0.     0.2195 0.6632]
 [0.     0.2475 0.     0.6114 0.3877 0.6114 0.2023 0.    ]
 [0.     0.     0.6404 0.6404 0.     0.     0.4239 0.    ]]
